name: another-action
run-name: another-action
on: [push]
jobs:
  what-is-there:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name:  check
        env:
          SECRET_ENV: ${{secrets.SECRET_ENV}}
          REPO_ENV: ${{vars.REPO_ENV}}
        run: env


